### ISSUE TITLE
XML error and no HTML attachment

### ISSUE THREAD

**Issue by cyborghound** [essenius/FitNesseRun#8] opened 2020-02-20 08:15 UTC
I'm trying to run the FitNesse Run task in an on-premises  azure devops environment. I configured everything like the manual from this Git.

I  have two issues which I found. The first one is the error is Cannot convert value "<?xml version="1.0"?> which causes to not create a nunit file and no test report. This issue is only in some test runs, but not on every run.

The second issue I have is when the test run is good and not causing the error I talked about before, then I only have a nunit file ad test report, but am missing the html and fitnesse.xml attachments.

I checked the html option and have the 3 files in the result folder in the workspace.

**Comment by gokusupa** [comment] 2020-03-04 13:02
I too, continue to have this issue. "Cannot convert value" and it dumps a buncha XML to my Azure devops release log.  Happens every once and a while.

It's so bad at this point I might consider removing this app and going back to manual executions.

**Comment by gokusupa** [comment] 2020-03-06 16:32
I really think the size of the suite is a part of the problem. I've been testing with a much smaller smoke suite trying to re-produce the problem and I am unable. 

Going to test a workaround of splitting up our suite into smaller sub test suites, see if this helps.

**Comment by gokusupa** [comment] 2020-03-09 16:00
I have a working theory on the issue. According to the Fitnesse documentation around the "includehtml" flag it says, "includehtml - If format=xml then this will cause the XML to contain a 'content' tag that holds the HTML of the tested page. Beware, this can lead to OutOfMemory errors for large suites. See (http://fitnesse.org/FitNesse.UserGuide.AdministeringFitNesse.RestfulServices)

I noticed on line 327 of your fitnesserun.ps1 file that the following command execution line always includes this parameter. Regardless if "includeHTML" is checked or unchcecked in your FitnesseRun task within the azure devops task itself 

https://github.com/essenius/FitNesseRun/blob/b693d3747d38913e4f35489641ad1e0c33412d32/FitNesseRun/FitNesseRunV1/FitNesseRun.ps1#L327

In the Debug logs for the task I can see that even though the task is set to not include the HTML, the command executes with this fitnesse flag enabled.

2020-03-09T14:31:59.2019093Z ##[debug]SYSTEM_CULTURE: 'en-US'
2020-03-09T14:31:59.2571649Z ##[debug]INPUT_COMMAND: 'execute'
2020-03-09T14:31:59.2663886Z ##[debug]INPUT_TESTSPEC: 'ChangeAuditor:suite'
**2020-03-09T14:31:59.2690505Z ##[debug]INPUT_INCLUDEHTML: 'false'**
2020-03-09T14:31:59.2725274Z ##[debug]INPUT_RESULTFOLDER: 'C:\FitNesse'
2020-03-09T14:31:59.2754091Z ##[debug]INPUT_EXTRAPARAM (empty)
2020-03-09T14:31:59.2803332Z ##[debug]INPUT_PORT: '8080'
2020-03-09T14:31:59.2830696Z ##[debug]INPUT_DATAFOLDER: 'C:\FitNesse'
2020-03-09T14:31:59.2859408Z ##[debug]INPUT_APPSEARCHROOT: 'C:\FitNesse'
2020-03-09T14:31:59.2883173Z ##[debug]INPUT_BASEURI: 'http://localhost:8080'
2020-03-09T14:31:59.2916795Z ##[debug]INPUT_TIMEOUTSECONDS: 'Default'
2020-03-09T14:31:59.2950065Z ##[debug]Leaving Get-TaskParameter.
2020-03-09T14:31:59.3141819Z ##[debug]Invoking FitNesse
2020-03-09T14:31:59.5739037Z ##[debug]Executing [C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe] [C:\FitNesse\fitnesse-standalone.jar], port=[8080], data@[C:\FitNesse], command=[ChangeAuditor?suite&format=xml&nochunk&**includehtml**]
2020-03-09T14:31:59.5834424Z ##[Command]Executing: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe -jar "C:\FitNesse\fitnesse-standalone.jar" -d "C:\FitNesse" -p 8080 -o -c "ChangeAuditor?suite&format=xml&nochunk&**includehtml**"

I have still yet to decide how I will continue.

**Comment by essenius** [comment] 2020-03-15 11:50
Indeed the only thing that this parameter controls right now is creating an HTML results file or not. I'll have a look whether it's easy to change the way FitNesse is called as well.

**Comment by essenius** [comment] 2020-03-16 14:34
I've just uploaded v1.0.32 to the market place. This version no longer asks FitNesse to include HTML for suites if the "Include HTML" flag is off. @gokusupa @Blackpander I hope this helps fixing your issue.

**Comment by gokusupa** [comment] 2020-03-26 09:56
I'm excited to try it today my friend! I will be rolling this back out today and I will report back with results.

**Comment by gokusupa** [comment] 2020-03-26 13:07
Unfortunatly this did not fix the issue. I did confirm the command is now formatted correct with out the HTML included but I am still seeing the problem. 

2020-03-26T12:54:13.9406045Z ##[error]Cannot convert value "<?xml version="1.0"?>

**Comment by essenius** [comment] 2020-03-30 07:29
@gokusupa Is there any way you can provide a reproducible case for this? I've never seen it happen and would like to understand the root cause.

**Comment by gokusupa** [comment] 2020-03-31 17:23
It seems to be happening quite alot in our large primary testing suite. We have a smaller test smoke suite that executes for less than 3-5 min and it's quite solid when using it last I remember. It's when our large primary test suite (which can take an hour and a half) to execute, this issue occurs.

That is all I have right now, next chance I get I can try and slowly increase the suite execution time by adding simple tests to see if I can narrow it down when exactly it will start failing. All I know now currently is size is a factor I think. But before I can say for sure, I would like to remove my product powershell code and add just simple windows powershell test executions so I can post the suite here for you to use for re-production.

FYI were using Powerslim plugin for fitnesse to test powershell code.

**Comment by gokusupa** [comment] 2020-04-14 16:07
So I finally had some time to look deeper into this issue. I wanted to upload the Fitnesse suite I used to reproduce the issue in my own lab for your use.

A larger lab can generate the problem, you can download the fitnesse suite I used to generate the issue [HERE ](https://drive.google.com/file/d/1EN_OTvSoOZaaRVUXdljvm-UAcbUs-LYx/view?usp=sharing)for your own reproduction. I first created a simple fitnesse test, then replicated that test several times adding a number on the end of the name to create 3000 tests. I then execute the suite using the "fitnesseRun" task. I was able to easily generate the problem on a suite that takes 30 min to execute.

You can take the same test suite and leave only a few test wikis, and you will see the same smaller test suite work without the problem detailed in this case.

My Fitnesse version is release v20191110. Also as mentioned before we are testing using powershell and the Powerslim extension (https://github.com/konstantinvlasenko/PowerSlim)

**Comment by essenius** [comment] 2020-05-04 19:31
@gokusupa Thanks, I'll have a look.

**Comment by essenius** [comment] 2020-05-12 06:10
@gokusupa I was able to reproduce the issue with suites having large numbers of tests. In my tests it started to occur with 4k tests. To be able to read both the error stream and the output stream FitNesseRun reads one stream synchronously and one asynchronously. Apparently the asynchronous read is a bit flaky with large volumes. I flipped the redirects to make output read synchronously, and since then I didn't see the issue anymore. I tested with suites of up to 16k tests (the output stream was 6,5MB) without problems. I uploaded a new version (1.0.37) in the Marketplace. Can you have another look?

**Comment by essenius** [comment] 2020-05-12 06:11
By the way, I did see that the time per test increases linearly with the number of test pages  in a suite - the 16k test took about 4 times as long as the 8k test, and the 8k test took about 4 times as long as the 4k test. So it's probably a good idea to keep the number of tests per suite within the three digits, and splitting up large batches makes a lot of sense performance wise.

**Comment by gokusupa** [comment] 2020-05-20 13:29
I will give this a try first thing and report back ! So glad to hear this news.

**Comment by gokusupa** [comment] 2020-05-20 17:04
First run was a success! Running it a few more times for good measure.

**Comment by gokusupa** [comment] 2020-05-21 09:56
The bug is now resolved IMO. But another bug has surfaced since this change, I will log another issue to cover this.

It seems that the detailed HTML report is not longer giving all the details. Prior to the changes the entire fitnesse pages would be shown in detail for each and every test, showing what failed and why. Tests that passed were even shown in 100% detail. Now the are only displaying the name of the test and no other test data.

Below is and example of what is shown currently
![image](https://user-images.githubusercontent.com/26933360/82547190-b32c1400-9b2f-11ea-973a-91538454319b.png)

**Comment by essenius** [comment] 2020-05-25 07:16
Thanks, I'll close this issue.

**Closed as completed by essenius** 2020-05-25 07:16 UTC
